Добавлены лабы design и select
romansimakov/RedDatabaseLab pull request #2
Opened 2023-12-18 12:06 UTC by rodionveretin

2023-12-18 16:49 UTC, romansimakov requested changes

2023-12-18 16:49 UTC, romansimakov commented on .gitignore
> +.vscode/settings.json
а может и не игнорить их а закомитить? пусть будет настроенный проект)

2023-12-18 16:49 UTC, romansimakov commented on docs/design.rst
> +2.  Установить JDK не ниже 1.8
табуляция поехала

2023-12-21 07:30 UTC, rodionveretin commented on docs/design.rst
> +2.  Установить JDK не ниже 1.8
исправил

2023-12-21 07:31 UTC, rodionveretin commented on .gitignore
> +.vscode/settings.json
В этом файле были настройки плагина live просмотра .rst файлов, проект не настраивал

2024-12-08 07:57 UTC, closed without merging